use_frameworks!

def import_pods
    pod 'PorterStemmer2', :path => '../'
end

target 'PorterStemmer2_Example_iOS' do
    platform :ios, '9.0'
    import_pods

    target 'PorterStemmer2_Example_iOS_Tests' do
        inherit! :search_paths
    end

end

target 'PorterStemmer2_Example_OSX' do
    platform :osx, '10.10'
    import_pods    
end

